apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-video-eureka-out
  name: java-video-eureka-out
  namespace: video-prod
spec:
  ports:
  - nodePort: 30001
    port: 8035
    protocol: TCP
    targetPort: 8035
  selector:
    app: java-video-eureka
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-video-eureka
  name: java-video-eureka
  namespace: video-prod
spec:
  ports:
  - port: 8035
    protocol: TCP
    targetPort: 8035
  clusterIP: None
  selector:
    app: java-video-eureka