apiVersion: v1
kind: Service
metadata:
  labels:
    app: openresty
  name: openresty
  namespace: video-prod
spec:
  ports:
  - nodePort: 30006
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openresty
  type: NodePort