apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-video-center
  name: java-video-center
  namespace: video-prod
spec:
  ports:
  - nodePort: 30004
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: java-video-center
  type: NodePort