apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-video-common
  name: java-video-common
  namespace: video-prod
spec:
  ports:
  - nodePort: 30005
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: java-video-common
  type: NodePort