apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-video-admin
  name: java-video-admin
  namespace: video-prod
spec:
  ports:
  - nodePort: 30003
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-video-admin
  type: NodePort