apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: front-video
  name: front-video
  namespace: video-prod
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: front-video
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-video
    spec:
      containers:
        - env:
          image: >-
            registry-vpc.cn-shenzhen.aliyuncs.com/xb-video/front-video:201909231359
          imagePullPolicy: Always
          lifecycle:
            preStop:
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: front-video
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: 1500Mi
          volumeMounts:
            - mountPath: /usr/local/front-video/nginx/logs/
              name: front-video-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: java-vidoe
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: front-video-logs