apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: java-video-web
  name: java-video-web
  namespace: video-prod
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-video-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-video-web
    spec:
      containers:
        - env:
            - name: JAVA_HOME
              value: /opt/app/java
            - name: aliyun_logs_java-cloud_stdout
              value: java-cloud-eureka
            - name: aliyun_logs_java-cloud_accesslog
              value: accesslog
          image: >-
            registry-vpc.cn-shenzhen.aliyuncs.com/xb-video/java-video-web:201909231130
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - curl
                  - '-sv'
                  - '-X'
                  - POST
                  - 'http://localhost:4040/monitor/shutdown'
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: java-video-web
          ports:
            - containerPort: 8090
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: 1500Mi
          volumeMounts:
            - mountPath: /opt/data/jars/logs
              name: java-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: java-vidoe
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: java-logs